services:
  - type: web
    name: odoo
    env: docker
    repo: https://github.com/chintooflutter/odoo/
    branch: 18.0  # Change to match your repo branch
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_HOST
        fromService:
          type: pserv
          name: odoo-db
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: odoo-db
          property: port
      - key: DB_USER
        value: odoo
      - key: DB_PASSWORD
        fromDatabase:
          name: odoo-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: odoo-db
          property: database

databases:
  - name: odoo-db
    databaseName: odoo
    user: odoo
